added cpp/matthewrolls solution, associated items
sleddog/methods-spring-2024 pull request #55
Opened 2024-03-04 22:29 UTC by mrolls13

2024-03-19 20:51 UTC, LukasB4 commented
+1 Good code

2024-03-19 20:52 UTC, LukasB4 approved these changes

2024-03-19 23:19 UTC, yabets-ebren commented
It didn't work when i run the script locally. Segmentation fault

<img width="874" alt="Screenshot 2024-03-19 at 5 18 15 PM" src="https://github.com/sleddog/methods-spring-2024/assets/71809265/44ac7387-4c6c-4278-8715-e50e66a22428">

2024-03-19 23:33 UTC, mrolls13 commented
> It didn't work when i run the script locally. Segmentation fault. You may want to look in to that.
> <img alt="Screenshot 2024-03-19 at 5 18 15 PM" width="874" src="https://private-user-images.githubusercontent.com/71809265/314261203-44ac7387-4c6c-4278-8715-e50e66a22428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTExNjQsIm5iZiI6MTcxMDg5MDg2NCwicGF0aCI6Ii83MTgwOTI2NS8zMTQyNjEyMDMtNDRhYzczODctNGM2Yy00Mjc4LTg3MTUtZTUwZTY2YTIyNDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIzMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMTRjYmZmMDVkZmYyMmEyNzMyOTcwZGRkNWE0Y2UwMTM2MWJkYjg2ODJmYTAzNWMxZWIyNzg4ZTRiMjliZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V0ZO9JDqnxuyW2vkmTyrFEGsmq_pWHZCveLSy3euQAE">

It still runs in my vm, I might have messed up something when transferring it. I'll look into it.

2024-03-20 00:22 UTC, Jake-Ripley commented
Solution doesn't work, segmentation fault
<img width="488" alt="Screenshot 2024-03-19 at 6 21 43 PM" src="https://github.com/sleddog/methods-spring-2024/assets/124402094/a6f8cfd6-7777-4b04-9de7-3567f3b78da4">

2024-03-20 00:38 UTC, mrolls13 commented
> Solution doesn't work, segmentation fault <img alt="Screenshot 2024-03-19 at 6 21 43 PM" width="488" src="https://private-user-images.githubusercontent.com/124402094/314282851-a6f8cfd6-7777-4b04-9de7-3567f3b78da4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTQ4MTQsIm5iZiI6MTcxMDg5NDUxNCwicGF0aCI6Ii8xMjQ0MDIwOTQvMzE0MjgyODUxLWE2ZjhjZmQ2LTc3NzctNGIwNC05ZGU3LTM1NjdmM2I3OGRhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwMDI4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmUxMjg5MzA5ZTYzZjEwYjRhODE1OWYyYzRiNjQ4ZjRiNTRmZjdjYTYxZmUwNmNjOTFiN2E4NGIyY2YzZGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SVNBmqmzotf21UJQTemg2zW5cwNlCxEghnz-qPkVSgk">

![Screenshot (946)](https://github.com/sleddog/methods-spring-2024/assets/106624538/e37c7f4f-d36a-4c70-b2bb-b4f906e5f625)
 This is using the linux vm for csci476

2024-03-23 19:27 UTC, Jake-Ripley approved these changes
+1 looks good

2024-03-23 19:39 UTC, sleddog commented on problems/fizzbuzz/cpp/matthewrolls/script.sh
> +echo Enter number
do not ask the number here during the script.  this should be passed as an argument to the shell script:  `./script.sh 16`

2024-03-23 19:40 UTC, sleddog commented on problems/fizzbuzz/cpp/matthewrolls/script.sh
> +./fzbz-mr $num
pass the value using `$1`:   `./fzbz-mr $1`

2024-03-23 20:05 UTC, sleddog requested changes
please make the changes requested above

2024-03-23 20:06 UTC, sleddog commented on problems/fizzbuzz/cpp/matthewrolls/fzbz-mr.cpp
> +	}
these tests should be in a separate file

2024-03-24 00:28 UTC, sleddog commented
+10 
![image](https://github.com/sleddog/methods-spring-2024/assets/38183/c5184fd1-0f0a-4993-bf43-574e9bc96a45)

2024-03-24 00:30 UTC, sleddog approved these changes
+1

2024-03-24 00:34 UTC, merged